services:
  ktoolbox:
    build: .
    container_name: ktoolbox
    user: 1000:1000
    volumes:
      - /path/to/downloads:/downloads
    command:
      [
        "download-post",
        "https://kemono.su/fanbox/user/49494721/post/6608808"
      ]
